spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true
    username: microservice
    password: Micro123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
